services:
  database:
    image: postgres:16.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - sq-backend-dev-database:/var/lib/postgresql/data

volumes:
  sq-backend-dev-database: